version: '2'
services:

    web:
        image: venveo/craftcms:5.5
        ports:
            - "8000:80"
        depends_on:
            - mysql
        links:
            - mysql
        volumes:
            - .:/var/www:rw
            - ./public:/var/www/html:ro
        env_file: .env

    mysql:
        image: mysql:5.5.50
        ports:
            - "3306:3306"
        volumes:
            - "./storage/database:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: SuperLongPassword!
            MYSQL_DATABASE: dev_craftcms
            MYSQL_PASSWORD: Password1!
            MYSQL_USER: craftcms
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
